[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "18.20.4"
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/course/data-science"
  to = "/data-science-course"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}